name: trivy-pr-scan 
on:
  workflow_call:
  pull_request:
    # branches:
    #   - develop
    #   - master
    #   - main 
    # types: [ opened, synchronize ]
    # paths-ignore:
    # - README.md
    # - .old_cicd/*
    # - .github/*
    # - .github/workflows/*
    # - LICENSE
    # - .gitignore
    # - .dockerignore
    # - .githooks

jobs:
 trivy-pr-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # We will not be concerned with Medium and Low vulnerabilities
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'sarif'
        severity: 'CRITICAL,HIGH'
        output: 'trivy-results.sarif'
        exit-code: '1'
    # Scan results should be viewable in GitHub Security Dashboard
    # We still fail the job if results are found, so below will always run
    # unless manually canceled.
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: '!cancelled()'
      with:
        sarif_file: 'trivy-results.sarif'